# Generated by Django 2.2.24 on 2022-06-12 20:48
import phonenumbers
from django.db import migrations


def parse_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.owner_pure_phone  = phonenumbers.parse(
            flat.owners_phonenumber,
            'RU'
        )

        if phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220612_2346'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumber)
    ]
