# Generated by Django 2.2.24 on 2022-06-12 21:41

from django.db import migrations


def set_flat_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        if owner:
            owner.owned_flats.add(flat)
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220613_0032'),
    ]

    operations = [
        migrations.RunPython(set_flat_to_owner)
    ]
