# Generated by Django 2.2.24 on 2022-06-12 22:20

from django.db import migrations

def set_owners_full_name(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            phonenumber=flat.owners_phonenumber
        )
        if owner:
            owner.full_name = flat.owner
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220613_0119'),
    ]

    operations = [
        migrations.RunPython(set_owners_full_name)
    ]
