# Generated by Django 2.2.24 on 2022-06-12 22:32

from django.db import migrations


def set_flat_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner = Owner.objects.get(
            phonenumber=flat.owners_phonenumber
        )
        if owner:
            owner.full_name = flat.owner
            owner.save()

    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner = Owner.objects.get(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        if owner:
            owner.flats.add(flat)
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220613_0119'),
    ]

    operations = [
        migrations.RunPython(set_flat_to_owner)
    ]
